[project]
name = "unicode_palette"
version = "2023.12.17"
description = "Unicode character palettte as a data: URL."

[project.scripts]
unicode_palette = "unicode_palette.unicode_palette:main"

[tool.setuptools.packages.find]
where = ["src"]
